FROM ubuntu:latest

RUN apt-get update \
    && apt-get install -y libapache2-mod-php apache2 php-memcache \
    && rm -fr /var/www/html

COPY memadmin/ /var/www/html

CMD service apache2 restart && tail -f /var/log/apache2/access.log