#!/usr/bin/env bash

function env2py()
{
    (
    echo '# This file is an AUTOGENERATED part of quicksave project.'
    echo '# Copyright (c) 2017 Aleksander Gajewski <adiog@quicksave.io>.'
    echo ''
    echo 'import os'
    echo ''
    echo ''
    cat tmp/trash/env_string.in | sed -e "s|export \([^=]*\)=\"\([^\"]*\)\" *#* *\(.*\)|\1 = os.environ.get('\1', '\2')|" | envsubst
    cat tmp/trash/env_int.in | sed -e "s|export \([^=]*\)=\([0-9]*\) *#* *\(.*\)|\1 = int(os.environ.get('\1', '\2'))|" | envsubst
    ) > $1
}

env2py $1