FROM quicksave/dev-curl

RUN mkdir -p /keys
RUN mkdir -p /sshfs

RUN apt update && apt-get install -y phantomjs ffmpeg libav-tools

RUN virtualenv -p python3.6 venv \
    && . venv/bin/activate \
    && pip3 install youtube_dl \
    && pip3 install git+https://github.com/adiog/io_quicksave_pybeans --upgrade \
    && pip3 install git+https://github.com/adiog/io_quicksave_async --upgrade

COPY storage_id_rsa /
COPY storage_id_rsa.pub /

RUN mkdir -p ~/.ssh \
    && mkdir -p /storage \
    && chmod 700 storage_id_rsa  storage_id_rsa.pub

CMD . venv/bin/activate \
    && ssh-keyscan storage_quicksave_docker >> ~/.ssh/known_hosts \
    && sshfs storage_quicksave_docker:/storage /storage/ -o IdentityFile=/storage_id_rsa -o idmap=user  \
    && export IO_QUICKSAVE_MQ_HOST=mq_quicksave_docker \
    && export IO_QUICKSAVE_MQ_PORT=5672 \
    && export QT_QPA_PLATFORM=offscreen \
    && qs-async \\
    || qs-audit fatal "quicksave post crashed" && bash
