FROM quicksave/dev-python

RUN mkdir -p /keys
RUN mkdir -p /sshfs

RUN apt-get install phantomjs virtualenv sshfs youtube-dl -y

RUN virtualenv -p python3.6 venv \
    && . venv/bin/activate \
    && pip3 install git+https://github.com/adiog/io_quicksave_pybeans --upgrade \
    && pip3 install git+https://github.com/adiog/io_quicksave_async.git --upgrade

COPY storage_id_rsa /
COPY storage_id_rsa.pub /

CMD . venv/bin/activate \
    && mkdir ~/.ssh \
    && mkdir -p /storage \
    && ssh-keyscan storage_quicksave_docker >> ~/.ssh/known_hosts \
    && sshfs storage_quicksave_docker:/storage /storage/ -o IdentityFile=/storage_id_rsa -o idmap=user  \
    && export IO_QUICKSAVE_MQ_HOST=mq_quicksave_docker \
    && export IO_QUICKSAVE_MQ_PORT=5672 \
    && export QT_QPA_PLATFORM=offscreen \
    && qs-async
